spring:
  application:
    name: spring-boot-payment
  profiles:
    active: dev,unionpay-dev

# Http Connection Pool
httpClient.connection.pool.size: 10
httpClientFactory:
  connection:
    timeout: 80000
  read:
    timeout: 80000

